<?php
include('include/header.php');
?>
<header class="header-page-bg overlay-shape">

    <div class="header-bottom-shape"></div>
    <div class="container">
        <div class="header-page-content">
            <small class="line-shape-bg color-white">Cysec</small>
            <h1 class="color-white">Service Details</h1>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="index.php">Home</a></li>
                    <li class="breadcrumb-item"><a href="Web Design & Development.php">Services</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Choose Strong Passwords</li>
                </ol>
            </nav>
        </div>
    </div>
</header>


<div class="service-details-section pt-100 pb-70">
    <div class="container">
        <div class="row">
            <div class=" col-md-6 ">
                <div class="service-details-item">
                    <div class="service-details-content">
                        <h3>Static Website Design</h3>
                        <p class="title-sub-text">A static website contains web pages with fixed code and data the data
                            of each page does not change unless it is manually updated by a web developer. Static web
                            sites are normally designed using web templates. Each page is coded in HTML and displays the
                            same information to every visitor. Static sites are the most basic type of website and are
                            the easiest to create. Static website is simple websites which are cost
                            effective.<br>Delight Media is a web design &amp; development company in Vapi, Guarat, and
                            Mumbai, India. We offer a various products and services, which include website design,
                            website development &amp; SEO services. With the ever-evolving business technologies and
                            widespread digitization, there have been considerable transformations in business marketing.
                            Enterprises today wish to establish a strong digital presence, thus creating a unique impact
                            on their customers’ mind. It is here that they require building attractive, compelling, and
                            appealing business websites capable of captivating the attention of their target audience.
                        </p>
                        <a href="request-quote.php"><button class="btn btn-theme btn-theme-md">REQUEST A
                                QUOTE</button></a>
                    </div>
                </div>
            </div>
            <div class=" col-md-6 ">
                <div class="service-details-item">
                    <div class="service-details-thumb">

                        <img src="assets/images/service1.jpg" alt style="width:100%;">
                    </div>

                </div>
            </div>
            <div class=" col-md-6 ">
                <div class="service-details-item">
                    <div class="service-details-content">
                        <h3 style="margin-top:20px">Dynamic Website Design</h3>
                        <p class="title-sub-text">A dynamic web page is a web page with web content that varies based on
                            parameters provided by a user or a computer program. In today's world the demand for dynamic
                            website is increasing at an alarming rate. Nowadays nearly half the websites are dynamic.
                            Pages are no longer static HTML files but instead generated by scripts and database calls.
                            Although dynamic websites are expensive as compared to static websites, it brings along with
                            it numerous features and advantages.</p>
                        <p class="title-sub-text">An era of evolution in probably all genres, especially in the fields
                            that need specific digital marketing strategies, all have taken to the most viable mode.
                            Well, you might think what this viable mode is? Living in this 21st century, after the speed
                            of light, the technological speed is the most feasible in all sectors. Hence, therefore it
                            is rightly administered that all genres have taken to the most sustainable mode. Catering to
                            this sustainable way, the Delight Media has enabled its customers to view them worldwide
                            with a strong digital presence. With an attractively built website that is appealing,
                            compelling and business oriented, the company is moving with some specific strategies.</p>
                        <a href="request-quote.php"><button class="btn btn-theme btn-theme-md">REQUEST A
                                QUOTE</button></a>
                    </div>
                </div>
            </div>
            <div class=" col-md-6 ">
                <div class="service-details-item">
                    <div class="service-details-thumb">

                        <img src="assets/images/service1.jpg" alt style="width:100%;">
                    </div>

                </div>
            </div>


        </div>

    </div>
</div>



<?php
include('include/footer.php');
?>